### ISSUE TITLE
无法引用retrofit2

### ISSUE THREAD

**Issue by LiLeiAndroid** [cn-ljb/mvp-kotlin#3]
在app  build.gradle中同时引用了
    //net lib
    implementation 'com.github.cn-ljb:netlib:1.0.0'
    //dao lib
    implementation 'com.github.cn-ljb:daolib:1.0.0'
此时出现Unresolved reference：retrofit2
删除dao lib引用后sync project，就可以找到retrofit，请问这是哪里冲突了吗？谢谢

**Comment by cn-ljb** [comment]
你好，
我尝试新建了Kotlin语言和Java语言项目，没有复现你的问题，
发现个小问题 Java code模版对jetbrains @NotNull注解有依赖，我会在下个小版本解决。

你那面能提供更详细的 build.gradle 配置 和 log信息吗？

**Comment by cn-ljb** [comment]
你好，

是netlib的问题
这两天正在优化netlib和daolib代码，在之后的小版本更新中会解决该问题。
你可以先在自己的主Module中单独引入retrofit2：

 implementation 'com.squareup.retrofit2:retrofit:2.4.0'

或者在明后天发布新的netlib和daolib后，更新到对应新版本。

谢谢！

**Comment by LiLeiAndroid** [comment]
你好，我降低了gradle的版本，现在使用的是4.4就没问题了

distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
classpath 'com.android.tools.build:gradle:3.1.3'

**Comment by cn-ljb** [comment]
主要原因还是lib中的build.gradle配置有问题，这两天我会修改 ∩_∩、、

**Comment by cn-ljb** [comment]
lib可以更新到 v1.0.1 版本了

//net lib
implementation 'com.github.cn-ljb:netlib:1.0.1'
//dao lib
implementation 'com.github.cn-ljb:daolib:1.0.1'
