### ISSUE TITLE
demo中列表页加载更多，出错后，page还是++，导致跳页

### ISSUE THREAD

**Issue by android-1995** [cn-ljb/mvp-kotlin#4]

**Comment by android-1995** [comment]
还有一个问题，如何扩展基类的方法？
举个例子：我想在BaseMvpAppCompatActivity这个类像showToast这个方法一样扩展showLoadingDialog方法。
目前我就只能想到导入代码修改IViewContract接口，或者写个类MyIViewContract,然后在每个Contract的IView都继承MyIViewContract，但是这样很麻烦，每个activity实例都需要重写showLoadingDialog方法
求解~谢谢

**Comment by cn-ljb** [comment]
现在扩展只能是你说的那两种方法，建议用前者，只要基础库包名不变，插件依旧可以使用。

后续版本考虑在不动mvplib基础上，提供扩展方案。

（如果有兴趣，也可以修改插件库代码，生成自己的mvp模版）

谢谢~

**Comment by android-1995** [comment]
期待后续更新，感谢开源~
