### ISSUE TITLE
待更新

### ISSUE THREAD

**Issue by cn-ljb** [cn-ljb/mvp-kotlin#5]
1、Presenter getContext()优化，方便java代码调用
2、提供更简易扩展公共IView接口

**Comment by android-1995** [comment]
> 2、提供更简易扩展公共IView接口

这个需求如果用kotlin的扩展baseAct的函数来实现会如何？

**Comment by cn-ljb** [comment]
使用Kotlin扩展方法是可以的实现功能。
但对于架构设计来说还是不太友好，就想第一条要优化的Presenter.getContextEx()方法一样，它在实际编译完后其实是个静态方法，Java调用很不友好。

**Comment by cn-ljb** [comment]
最近工作太忙，可能会耽搁一段时间更新

**Comment by vkxing** [comment]
我想在base类里面加加一些方法，如何去实现呢

**Comment by cn-ljb** [comment]
三种方案：
1、不使用代码生成插件，自己继承添加扩展功能
2、修改插件代码，以你的新Base类做模板
3、下载mvp-core修改里面的base类（这种简单点）
