### ISSUE TITLE
能把BaseMvpActivity暴露出来出来吗？

### ISSUE THREAD

**Issue by WenChaoLuo** [cn-ljb/mvp-kotlin#6]
有些操作需要在BaseMvpActivity中编写

**Comment by WenChaoLuo** [comment]
![image](https://user-images.githubusercontent.com/23055446/62435402-9ffdb280-b76e-11e9-8b3a-19bd970687f1.png)
![image](https://user-images.githubusercontent.com/23055446/62435422-b277ec00-b76e-11e9-9343-949297865b0c.png)
还有在Activity中onCreate()方法没有执行？

**Comment by cn-ljb** [comment]
问题1：如果配合我的插件使用，你可以直接把 mvplib 这个库源码下载下来修改BaseMvpActivity；如果不使用我的插件，直接编写自己的BaseMvpActivity即可。

问题2：你覆写的onCreate()方法错了，需覆写单参数onCreate()方法。
